FROM eclipse-temurin:21-jdk

LABEL authors="devanshu"







# Set working directory
WORKDIR /app

COPY target/springSecurity-0.0.1-SNAPSHOT.jar





# Run the application
ENTRYPOINT ["java","-jar","app.jar"]